DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEM_NUM"	NUMBER(5)		NOT NULL,
	"MEM_ID"	VARCHAR2(10)		NOT NULL,
	"MEM_PASS"	VARCHAR2(10)		NOT NULL,
	"MEM_NAME"	VARCHAR2(10)		NOT NULL,
	"MEM_GENDER"	VARCHAR2(5)		NOT NULL,
	"MEM_HP"	NUMBER(12)		NULL,
	"MEM_BIR"	DATE		NULL,
	"MEM_ADD"	VARCHAR2(50)		NULL,
	"MEM_EMAIL"	VARCHAR2(40)		NULL
);

DROP TABLE "RENT";

CREATE TABLE "RENT" (
	"RENT_NUM"	NUMBER(10)		NOT NULL,
	"RENT_START"	DATE		NULL,
	"RENT_END"	DATE		NULL,
	"RENT_EXTEND"	VARCHAR2(10)		NULL,
	"MEM_NUM"	NUMBER(5)		NOT NULL,
	"BOOK_NUMBER"	NUMBER(10)		NOT NULL,
	"BOOK_RESERVATION"	DATE		NULL
);

DROP TABLE "BOOK";

CREATE TABLE "BOOK" (
	"BOOK_NUMBER"	NUMBER(10)		NOT NULL,
	"BOOK_NAME"	VARCHAR2(30)		NOT NULL,
	"BOOK_WRITER"	VARCHAR2(30)		NOT NULL,
	"BOOK_REGIST"	DATE		NOT NULL,
	"BOOK_ISBN"	NUMBER(12)		NULL,
	"BOOK_TYPE"	NUMBER		NOT NULL,
	"BOOK_POSITION"	VARCHAR2(20)		NULL
);

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NUM"	NUMBER(20)		NOT NULL,
	"BOARD_TYPE"	VARCHAR2(10)		NOT NULL
);

DROP TABLE "POST";

CREATE TABLE "POST" (
	"POST_NUM"	NUMBER(10)		NOT NULL,
	"POST_TITLE"	VARCHAR2(20)		NOT NULL,
	"POST_CONTENT"	VARCHAR2(400)		NOT NULL,
	"POST_DATE"	DATE		NOT NULL,
	"MEM_NUM"	NUMBER(5)		NOT NULL,
	"BOARD_NUM"	NUMBER(20)		NOT NULL
);

DROP TABLE "BOOK_TYPE";

CREATE TABLE "BOOK_TYPE" (
	"BOOK_TYPE"	NUMBER		NOT NULL,
	"BOOK_TYPENAME"	VARCHAR2(20)		NOT NULL
);

DROP TABLE "COMENT";

CREATE TABLE "COMENT" (
	"COMENT_NUM"	NUMBER(10)		NOT NULL,
	"COMENT_CONTENT"	VARCHAR2(200)		NOT NULL,
	"COMENT_DATE"	DATE		NOT NULL,
	"MEM_NUM"	NUMBER(5)		NOT NULL,
	"POST_NUM"	NUMBER(10)		NOT NULL
);

DROP TABLE "BOOK_STOCK";

CREATE TABLE "BOOK_STOCK" (
	"BOOK_NUMBER"	NUMBER(10)		NOT NULL,
	"BOOK_IN"	DATE		NULL,
	"BOOK_OUT"	DATE		NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_NUM"
);

ALTER TABLE "RENT" ADD CONSTRAINT "PK_RENT" PRIMARY KEY (
	"RENT_NUM"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (
	"BOOK_NUMBER"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NUM"
);

ALTER TABLE "POST" ADD CONSTRAINT "PK_POST" PRIMARY KEY (
	"POST_NUM"
);

ALTER TABLE "BOOK_TYPE" ADD CONSTRAINT "PK_BOOK_TYPE" PRIMARY KEY (
	"BOOK_TYPE"
);

ALTER TABLE "COMENT" ADD CONSTRAINT "PK_COMENT" PRIMARY KEY (
	"COMENT_NUM"
);

ALTER TABLE "BOOK_STOCK" ADD CONSTRAINT "PK_BOOK_STOCK" PRIMARY KEY (
	"BOOK_NUMBER"
);

ALTER TABLE "RENT" ADD CONSTRAINT "FK_MEMBER_TO_RENT_1" FOREIGN KEY (
	"MEM_NUM"
)
REFERENCES "MEMBER" (
	"MEM_NUM"
);

ALTER TABLE "RENT" ADD CONSTRAINT "FK_BOOK_TO_RENT_1" FOREIGN KEY (
	"BOOK_NUMBER"
)
REFERENCES "BOOK" (
	"BOOK_NUMBER"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "FK_BOOK_TYPE_TO_BOOK_1" FOREIGN KEY (
	"BOOK_TYPE"
)
REFERENCES "BOOK_TYPE" (
	"BOOK_TYPE"
);

ALTER TABLE "POST" ADD CONSTRAINT "FK_MEMBER_TO_POST_1" FOREIGN KEY (
	"MEM_NUM"
)
REFERENCES "MEMBER" (
	"MEM_NUM"
);

ALTER TABLE "POST" ADD CONSTRAINT "FK_BOARD_TO_POST_1" FOREIGN KEY (
	"BOARD_NUM"
)
REFERENCES "BOARD" (
	"BOARD_NUM"
);

ALTER TABLE "COMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMENT_1" FOREIGN KEY (
	"MEM_NUM"
)
REFERENCES "MEMBER" (
	"MEM_NUM"
);

ALTER TABLE "COMENT" ADD CONSTRAINT "FK_POST_TO_COMENT_1" FOREIGN KEY (
	"POST_NUM"
)
REFERENCES "POST" (
	"POST_NUM"
);

ALTER TABLE "BOOK_STOCK" ADD CONSTRAINT "FK_BOOK_TO_BOOK_STOCK_1" FOREIGN KEY (
	"BOOK_NUMBER"
)
REFERENCES "BOOK" (
	"BOOK_NUMBER"
);

